---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Copy CA files to the system
  copy:
    src: files/
    dest: "{{ ca_trusted_dir }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - update bundles
    - restart sssd
...
